version: "3.8"
services: 
  proxy:
    container_name: nginx
    build: 
      context: nginx/
    volumes:
      - ./logs:/var/log/nginx
      # - ./nginx/templates/:/etc/nginx/templates/ 
      - ./certs:/etc/nginx/certs/
      # - ./nginx/docker-entrypoint.d/env.sh:/docker-entrypoint.sh overwrite causing missing variable error
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST
    networks: 
      - kitty
  hello:
    container_name: hello
    image: dukecyber/http-go:v1.0-simple
    platform: linux/amd64
    ports:
      - "9000:9000"
    networks: 
      - kitty
networks:
  kitty: